# @package _global_
dataset:
  coeff: 8.0

model:
  encoder:
    seq_hidden_units: 24
    br_size: 24
    fc_hidden_units: 6
    dropout_rate: 0.1
    num_layer: 1
    batch_size: 128
    optimizer:
      learning_rate: 0.0001

    self_positional_encoding:
      max_relative_position: 15

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 512
    br_size: 3
    fc_hidden_units: 12
    dropout_rate: 0.2
    num_layer: 1

    cross_positional_encoding:
      max_relative_position: 15

exp:
  weights_ema: True
  alpha: 0.01
  beta: 0.99
  balancing: domain_confusion
  weight_bceloss: 1