# @package _global_
dataset:
  coeff: 6.0

model:
  encoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 256
    seq_hidden_units: 18
    br_size: 6
    fc_hidden_units: 12
    dropout_rate: 0.1

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.0001
    batch_size: 256
    br_size: 12
    fc_hidden_units: 3
    dropout_rate: 0.1

exp:
  weights_ema: False
  balancing: grad_reverse
  weight_bceloss: 1